services:
  app:
    container_name: "glpi-app"
    image: "glpi-vtt:latest"
    restart: "always"
    volumes:
      - "./config:/var/www/glpi/config"
      - "./data:/var/www/glpi/files"
      - "./plugins:/var/www/glpi/plugins"
      - "./marketplace:/var/www/glpi/marketplace"
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    container_name: "glpi-db"
    image: "mariadb:10.11"
    restart: "always"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: "i.m96M;.O)rK1&Pf.|nt(OS2£j~r:#e*"
      MARIADB_DATABASE: "glpidb"
      MARIADB_USER: "glpiuser"
      MARIADB_PASSWORD: "glpipassword"
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - mysql
